In [1]:
import torch
if torch.backends.mps.is_available():
    mps_device = torch.device("mps")
    x = torch.ones(1, device=mps_device)
    print (x)
else:
    print ("MPS device not found.")

tensor([1.], device='mps:0')


# Pytorch tensors & numpy

In [15]:
import numpy as np

array = np.arange(1., 8.) # Numpy's default dtype is float64, whereas torch's default array is float32
tensor = torch.from_numpy(array)
tensor.dtype # Torch reflefts this, so tensors created from np arrays are all of type float64

torch.float64

In [16]:
# Changing the value of the array doesn't affect the tensor
array = array + 1
array, tensor

array([2., 3., 4., 5., 6., 7., 8.])

In [18]:
# However, using the += method on the array does change the tensor as well
array = np.arange(1., 8.)
tensor = torch.from_numpy(array)
array += 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([2., 3., 4., 5., 6., 7., 8.], dtype=torch.float64))

In [19]:
# Tensor to numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor # Numpy array reflects torch's default dtype

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [20]:
tensor += 1

In [21]:
numpy_tensor

array([2., 2., 2., 2., 2., 2., 2.], dtype=float32)

# Seeding

In [22]:
# Complete randomness, hard to reproduce

a = torch.rand(3, 4)
b = torch.rand(3, 4)
a, b, a == b

(tensor([[0.9540, 0.8721, 0.0770, 0.0852],
         [0.5661, 0.2461, 0.3297, 0.6207],
         [0.1207, 0.7703, 0.3983, 0.0062]]),
 tensor([[0.5955, 0.8249, 0.2566, 0.7106],
         [0.7954, 0.2667, 0.2718, 0.4262],
         [0.8652, 0.8230, 0.8275, 0.4962]]),
 tensor([[False, False, False, False],
         [False, False, False, False],
         [False, False, False, False]]))

In [23]:
# Reproducible randomness
RANDOM_SEED = 42 # set random seed as global constant
torch.manual_seed(RANDOM_SEED) # Tell torch about random seed
c = torch.rand(3, 4)
torch.manual_seed(RANDOM_SEED) # Seed must be reset every time a new sequence is generated
# Or else, the randomly generated sequence won't be based on the seed
d = torch.rand(3, 4)
c, d, c==d

(tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]]))

# Put tensors & models on the GPU --> Faster computations

In [24]:
t = torch.tensor([1, 2, 3])
t.device # default location for tensors: cpu

device(type='cpu')

In [25]:
device = "mps"
t_gpu = t.to(device) # Move tensor to gpu

In [26]:
t_gpu.device

device(type='mps', index=0)

In [29]:
# Might need to move back to cpu for numpy computations because numpy only runs on cpu
t_gpu.numpy()


TypeError: can't convert mps:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [28]:
t_cpu = t_gpu.to("cpu") # move back to cpu
t_cpu.device

device(type='cpu')

In [30]:
t_cpu.numpy()

array([1, 2, 3])